services:
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: personal-website
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/apache2
